version: "3.9"
services:
  learngualapp:
    build: .
    image: app:learngualapp
    container_name: learngualapp_container

    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - PORT=8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django-learngualapp
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
